---
abstract: 'A parser for Genome Variation Format files.'
author:
  - 'Shawn Rynearson, C<< <shawn.rynerson at gmail.com> >>'
  - 'Shawn Rynearson <shawn.rynerson@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GVF-Parser
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
